import json
import logging
import re
from typing import Optional

import src.config
from src.agent_handoff import _extract_section
from src.llm import query_agent
from src.skills import SafeGitHub

logger = logging.getLogger("JanusPRReview")

_DIFF_PROMPT_CHAR_LIMIT = 8000

_CHECKBOX_RE = re.compile(r"^\s*[-*]\s*\[([ xX])\]\s*(.+)$")
_LINKED_ISSUE_RE = re.compile(r"(?:closes|fixes|resolves)\s+#(\d+)", re.IGNORECASE)


def parse_acceptance_criteria(issue_body: str) -> list:
    """Parses the issue's '## Acceptance Criteria' section into
    [{"text": str, "checked": bool}, ...]. The checked state reflects the issue
    author's pre-PR belief only — review_pr() always re-evaluates every
    criterion against the actual diff rather than trusting it."""
    section = _extract_section(issue_body, "Acceptance Criteria")
    if not section:
        return []
    criteria = []
    for line in section.splitlines():
        match = _CHECKBOX_RE.match(line)
        if match:
            text = match.group(2).strip()
            if text:
                criteria.append({"text": text, "checked": match.group(1).lower() == "x"})
    return criteria


def infer_linked_issue(pr_body: str) -> Optional[int]:
    """Finds a GitHub closing-keyword reference (Closes/Fixes/Resolves #N) in a PR body."""
    if not pr_body:
        return None
    match = _LINKED_ISSUE_RE.search(pr_body)
    return int(match.group(1)) if match else None


def _summarize_diff(files: list) -> str:
    parts = []
    for f in files:
        header = f"### {f.get('filename')} ({f.get('status')}, +{f.get('additions', 0)}/-{f.get('deletions', 0)})"
        patch = f.get("patch", "(no patch available — binary file or diff too large)")
        parts.append(f"{header}\n{patch}")
    return "\n\n".join(parts)


def _evaluate_criterion(criterion_text: str, diff_summary: str) -> dict:
    prompt = (
        f"Acceptance criterion:\n{criterion_text}\n\n"
        f"PR diff (per-file patches):\n{diff_summary}\n\n"
        "Does the diff satisfy this acceptance criterion? "
        'Respond with JSON only: {"met": true|false, "reasoning": "..."}'
    )
    raw = query_agent("critic", prompt)
    try:
        parsed = json.loads(raw)
        if not isinstance(parsed, dict):
            raise ValueError("critic response was valid JSON but not an object")
        met = bool(parsed.get("met", False))
        reasoning = str(parsed.get("reasoning", ""))
    except (json.JSONDecodeError, ValueError):
        # Fail CLOSED, unlike epistemic.py's fail-open-to-approve: a false "met"
        # here flows directly toward /merge unblocking, so a malformed critic
        # response must never be silently treated as satisfied.
        met, reasoning = False, raw
    return {"text": criterion_text, "met": met, "reasoning": reasoning}


def _build_review_comment(pr: dict, issue: dict, results: list, quality_notes: str, recommendation: str) -> str:
    if results:
        lines = [
            f"- [{'x' if r['met'] else ' '}] {r['text']}"
            f"{' — ' + r['reasoning'] if r['reasoning'] else ''}"
            for r in results
        ]
        criteria_section = "\n".join(lines)
    else:
        criteria_section = f"*No Acceptance Criteria section found on issue #{issue.get('number')}.*"

    return (
        f"## Acceptance Criteria Status\n\n{criteria_section}\n\n"
        f"## Code Quality Notes\n\n{quality_notes}\n\n"
        f"## Recommendation\n\n**{recommendation}**\n\n"
        "---\n"
        f"*Automated review generated by Project Janus for PR #{pr.get('number')} "
        f"against issue #{issue.get('number')}.*"
    )


def _verdict_key(repo: str, pr_number: int) -> str:
    return f"pr_review.{repo}.{pr_number}"


def _persist_verdict(repo: str, pr_number: int, verdict: dict) -> None:
    from src.database import set_system_config_value
    set_system_config_value(_verdict_key(repo, pr_number), json.dumps(verdict), is_agent=True)


def get_stored_verdict(repo: str, pr_number: int) -> Optional[dict]:
    from src.database import get_connection
    conn = get_connection(read_only_constitution=True)
    try:
        row = conn.execute(
            "SELECT config_value FROM system_config WHERE config_key = ?",
            (_verdict_key(repo, pr_number),),
        ).fetchone()
    finally:
        conn.close()
    if not row or not row[0]:
        return None
    try:
        return json.loads(row[0])
    except (json.JSONDecodeError, ValueError):
        return None


def clear_stored_verdict(repo: str, pr_number: int) -> None:
    from src.database import get_connection
    conn = get_connection(read_only_constitution=True)
    try:
        conn.execute(
            "DELETE FROM system_config WHERE config_key = ?",
            (_verdict_key(repo, pr_number),),
        )
        conn.commit()
    finally:
        conn.close()


def review_pr(
    pr_number: int,
    issue_number: int,
    repo: Optional[str] = None,
    party_id: Optional[str] = None,
    pr: Optional[dict] = None,
) -> dict:
    """Fetches a PR's diff and its originating issue, evaluates the diff against the
    issue's acceptance criteria via the critic agent, posts a structured review comment
    on the PR, and persists the verdict (bound to the PR's current head SHA, so a stale
    verdict from before new commits were pushed can't silently authorize a merge) for a
    later /merge command to consult.

    Pass pr= if the caller already fetched the PR (e.g. to infer issue_number from its
    body) to avoid a redundant GitHub API call."""
    repo = repo or src.config.GITHUB_REPO
    if not repo:
        raise ValueError("No repo configured: set GITHUB_REPO or pass repo=.")

    gh = SafeGitHub(party_id=party_id)
    pr = pr if pr is not None else gh.get_pr(repo, pr_number)
    files = gh.get_pr_diff(repo, pr_number)
    issue = gh.get_issue(repo, issue_number)

    diff_summary = _summarize_diff(files)[:_DIFF_PROMPT_CHAR_LIMIT]
    criteria = parse_acceptance_criteria(issue.get("body") or "")

    if not criteria:
        # No AC section to certify against — fail closed, don't skip-and-approve.
        results: list = []
        overall_met = False
    else:
        results = [_evaluate_criterion(c["text"], diff_summary) for c in criteria]
        overall_met = all(r["met"] for r in results)

    quality_notes = query_agent(
        "critic",
        "Review this PR diff for code quality (style, error handling, test "
        f"coverage, obvious bugs). Be concise (3-6 bullet points).\n\n{diff_summary}",
    )

    recommendation = (
        "APPROVE — ready to merge" if overall_met else "CHANGES REQUESTED — unmet acceptance criteria"
    )

    comment_body = _build_review_comment(pr, issue, results, quality_notes, recommendation)
    gh.add_comment(repo, pr_number, comment_body)

    verdict = {
        "repo": repo,
        "pr_number": pr_number,
        "issue_number": issue_number,
        "head_sha": (pr.get("head") or {}).get("sha"),
        "criteria": results,
        "overall_met": overall_met,
        "quality_notes": quality_notes,
        "recommendation": recommendation,
    }
    _persist_verdict(repo, pr_number, verdict)
    return verdict
